sites:
    - name: facebook
      url: www.facebook.com
      duration: 2024-12-19 14:59:42 +0700
      currentlyBlocked: false
    - name: youtube
      url: www.youtube.com
      duration: 2024-12-19 14:59:42 +0700
      currentlyBlocked: false
    - name: instagram
      url: www.instagram.com
      duration: 2024-12-19 14:59:42 +0700
      currentlyBlocked: false
