sites:
    - name: facebook
      url: www.facebook.com
      duration: 2024-12-13 15:57:54 +0700
      currentlyBlocked: false
    - name: youtube
      url: www.youtube.com
      duration: 2024-12-13 15:57:54 +0700
      currentlyBlocked: false
