sites:
    - name: youtube
      url: www.youtube.com
      duration: 2024-12-20 11:11:53 +0700
      currentlyBlocked: false
    - name: instagram
      url: www.instagram.com
      duration: 2024-12-20 11:11:53 +0700
      currentlyBlocked: false
    - name: facebook
      url: www.facebook.com
      duration: 2024-12-20 11:11:53 +0700
      currentlyBlocked: false
