sites:
    - www.facebook.com
    - www.youtube.com
    - www.instagram.com
schedules:
    friday:
        - start: "11:00"
          end: "11:48"
        - start: "13:00"
          end: "16:45"
        - start: "22:00"
          end: "23:51"
    monday:
        - start: "09:00"
          end: "17:00"
    saturday:
        - start: "10:00"
          end: "10:54"
    thursday:
        - start: "08:59"
          end: "11:00"
        - start: "13:00"
          end: "14:37"
current_status:
    started_at: time.....
    ended_at: 2024-12-21 10:54:00 +0700
    mode: normal
    block_on_restart: "false"
