sites:
  - www.facebook.com
  - www.instagram.com
  - www.youtube.com
schedules:
  friday:
    - start: "09:00"
      end: "11:48"
    - start: "13:00"
      end: "17:00"
  monday:
    - start: "09:00"
      end: "11:00"
    - start: "13:00"
      end: "17:00"
  thursday:
    - start: "09:00"
      end: "11:00"
    - start: "13:00"
      end: "18:02"
current_status:
  started_at: time.....
  mode: strict
